### ISSUE TITLE
Nao esta abrindo ordens para EURGBP

### ISSUE THREAD

**Issue by tanigutim** [abizinoto/BotMHI_IQOption#1]
![image](https://user-images.githubusercontent.com/67649006/86477602-21fbb000-bd1f-11ea-8879-92421fd17ca8.png)
hum... parece que o Label so quando abrir a issue..

**Comment by abizinoto** [comment]
Favor detalhar melhor o seu problema, senhor!!!

**Comment by tanigutim** [comment]
depois que conseguir colocar um Label.. kkk
