### ISSUE TITLE
Bot nao esta abrindo ordens

### ISSUE THREAD

**Issue by tanigutim** [abizinoto/BotMHI_IQOption#2]
no para EURUSD @abizinoto 
![image](https://user-images.githubusercontent.com/67649006/86493964-ec1ff100-bd49-11ea-9c2d-98d4fae2cbaa.png)
![image](https://user-images.githubusercontent.com/67649006/86493967-f04c0e80-bd49-11ea-9a5f-844728915fc3.png)

e sem nenhuma entrara ainda,  mesmo que tenha dado pelo setup

Parametros de  entrada:
 Indique uma paridade para operar: EURUSD
 Indique um valor para entrar: 50
 Indique a quantia de martingales (max 3): 1
 Indique o valor de Stop Loss: 900
 Indique o valor de Stop Gain: 2400
 Indique o Payout minimo para a operação: 84
 Considerar não operar com notícias acima de 1 touro? (S/N): N
 Indique o tipo de Opções (<B>inárias ou <D>igital: B

 Favor conferir os dados acima e digite [Sim] para prosseguir: Sim

**Comment by abizinoto** [comment]
Issue indentificado em https://github.com/abizinoto/bot-mhi-iqoption/issues/1
Fechando esse.
